config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :tasks do
    collection do
      delete 'delete_multiple'
      post :check_all
    end
  end

  # from todo to done
  get 'change_to_done/:id', to: 'tasks#change_to_done', as: 'change_to_done'
  # from done to todo
  get 'change_to_todo/:id', to: 'tasks#change_to_todo', as: 'change_to_todo'

  get 'check_all', to: 'task#check_all', as: 'check_all'
  root to: 'tasks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates :title, presence: true,
            length: { minimum: 3 }
  validates :priority, numericality: { only_integer: true }
  validate :due_date_cannot_be_in_the_past

  private
  def due_date_cannot_be_in_the_past
    if due.present? && due < Date.today
      errors.add(:due_date, "Due date can't be in the past")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :confirmable,
         :omniauth_providers => [:facebook]

  has_many :tasks

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
          uid: auth.uid,
          provider: auth.provider,
          email: User.dummy_email(auth),
          password: Devise.friendly_token[0, 20]
      )
    end

    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def full_name
    [first_name, last_name].join(' ')
  end

  def full_name=(name)
    elements = name.split(' ')
    self.last_name = elements.delete(elements.last)
    self.first_name = elements.join(" ")
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password) }
        end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  helper_method :sort_direction

  # GET /tasks
  # GET /tasks.json
  def index
    if params["sort"] == 'name'
      @tasks = Task.all.order('title ASC')
    elsif params[:sort] == 'created_at'
      @tasks = Task.all.order(:created_at)
    else
      @tasks = Task.all.order('title ASC')
    end
  end

  def index_sort_by_title
    Task.order('title ASC')
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id

    respond_to do |format|
      if @task.save
        format.html {redirect_to @task, notice: 'Task was successfully created.'}
        format.json {render :show, status: :created, location: @task}
      else
        format.html {render :new}
        format.json {render json: @task.errors, status: :unprocessable_entity}
      end
    end
  end


# PATCH/PUT /tasks/1
# PATCH/PUT /tasks/1.json
def update
  respond_to do |format|
    if @task.update(task_params)
      format.html {redirect_to @task, notice: 'Task was successfully updated.'}
      format.json {render :show, status: :ok, location: @task}
    else
      format.html {render :edit}
      format.json {render json: @task.errors, status: :unprocessable_entity}
    end
  end
end

# DELETE /tasks/1
# DELETE /tasks/1.json
def destroy
  @task.destroy
  respond_to do |format|
    format.html {redirect_to tasks_url, notice: 'Task was successfully destroyed.'}
    format.json {head :no_content}
  end
end

# POST change_to_done/:id'
# changes task's status from todo to done
def change_to_done
  @task = Task.find(params[:id])
  @task.done = true
  @task.save
  redirect_to root_path
end

# POST change_to_todo/:id
# changes task's status from done to todo
def change_to_todo
  @task = Task.find(params[:id])
  @task.done = false
  @task.save
  redirect_to root_path
end

def delete_multiple
  #@tasks = Task.find(params[:cb_tasks])
  #@tasks.destroy
  Task.where(id: params[:cb_tasks]).destroy_all
  respond_to do |format|
    format.html {redirect_to tasks_url, notice: 'Tasks was successfully destroyed.'}
    format.json {head :no_content}
  end
end

def check_all
  tags_id = params[:cb_tasks]
  if tags_id == '0'
    tags_id == '1'
  end
end

private
# Use callbacks to share common setup or constraints between actions.
def set_task
  @task = Task.find(params[:id])
end

# def task_params
#   params.require(:task).permit(:title, :description, :priority, :due, :done, :user_id)
# end
# Never trust parameters from the scary internet, only allow the white list through.
def task_params
  params.require(:task).permit(:title, :description, :priority, :due, :done, :user_id)
end

def sort_direction
  %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  def twitter
    callback_from :twitter
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => provider.capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(title, column, direction)
    direction = sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == 'desc' ? 'down' : 'up'

    link_to tasks_path, class: 'tiny button secondary', id: column do
      "#{title} &nbsp; <i class=fi-arrow-#{icon}></i>".html_safe
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestTodo</title>
    <%= csrf_meta_tags %>

        <!-- Bootstrap core CSS -->
    <link href="../../../../dist/css/bootstrap.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="col-md-2 col-md-offset-5">
  <%= form_with(model: task, local: true) do |form| %>
    <% if task.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

        <ul>
          <% task.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <table class="table table-striped">
      <div class="field">
        <tr>
          <td><%= form.label :title, class: "form-control "%>
          </td>
          <td>
            <%= form.text_field :title, id: :task_title %>
          </td>
        </tr>
      </div>

      <tr>
        <div class="field">
          <td><%= form.label :description %></td>
          <td><%= form.text_area :description, id: :task_description, class: "form-control", rows: 6 %></td>
        </div>
      </tr>
      <tr>
        <div class="field">
          <td><%= form.label :priority %></td>
          <td><%= form.number_field :priority, id: :task_priority, class: "form-control " %></td>
        </div>
      </tr>
      <tr>
        <div class="field">
          <td><%= form.label :due %></td>
          <td><%= form.date_field :due, id: :task_due, class: "form-control due_date datepicker", value: "#{@task.due ? @task.due.strftime("%d-%m-%Y") : Time.now.strftime("%d-%m-%Y")}" %></td>
        </div>
      </tr>
      <tr>
        <div class="field">
          <td><%= form.label :done %></td>
          <td><%= form.check_box :done, id: :task_done %></td>
        </div>
      </tr>
      <div class="actions">
        <%= form.submit %>
      </div>
    </table>

    <script>
        $(document).ready(function(){
            $('.datepicker').datepicker({
                dateFormat: "dd-mm-yy",
                minDate: new Date(),
            });
        });
    </script>

  <% end %>
</div>

app/views/tasks/completed-tasks.html.erb
<%= form_tag delete_multiple_tasks_path, method: :delete do %>

<!DOCTYPE html>
  <html lang="en">
  <head>
    <style>
      a.btn:not(.btn-info) {
        display: none;
      }

      .table, th, td:hover .btn {
        display: inline-block;
      }
    </style>
  </head>

  <div class="col-md-25 col-md-offset-1">
    <% if user_signed_in? %>
      <span>Hello, <%= current_user.email %></span>
      <%= link_to 'Log out', destroy_user_session_path, class: "btn btn-danger", :method => :delete %>
    <% else %>
      <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
      <%= link_to 'Log in', new_user_session_path %>
      or <%= link_to 'Registration', new_user_registration_path %>
    <% end %>


    <div class='container page-content' id='page-content'>
      <div id="flash-messages">
        <div class="alert alert-success alert-noajax">Signed in successfully.</div>
      </div>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <table class="table table-striped">

      <tr>
        Sort by
        <%= link_to 'Created Date', tasks_path(sort: 'created_at'), class: "btn btn-info" %>
        <br>
        <br>
        Sort by
        <%= link_to 'Title', tasks_path(sort: 'title'), class: "btn btn-info" %>


        <h2 class='page-heading'>Home</h2>
        <ul class='nav nav-tabs tasks-tabs' role='tablist'>
          <li class='active' role='presentation'>
            <a data-toggle='tab' href='#active-tasks'>Active tasks</a>
          </li>
          <li role='presentation'>
            <a data-toggle='tab' href='#completed-tasks'>Completed tasks</a>
          </li>
        </ul>

      </tr>
      <tr>
        <td class="col-md-1">ToDo</td>
      </tr>
      <% @tasks.each do |task| %>
        <tr>
          <% unless task.done %>
            <% if task.user_id == current_user.id %>
              <div class="row">
                <td><input type="checkbox" name="cb_tasks[]" id="tasks_" value="4" class="batch-del batch-del-checkbox" /></td>
                <td><%= check_box_tag "cb_tasks[]", task.id %>
                  <%= link_to task.title, task, class: "btn btn-info" %></td>
                <td><%= link_to 'Edit', edit_task_path(task.id), class: "btn btn-primary" %>
                  <%= link_to 'Mark as done', change_to_done_path(task.id), class: "btn btn-warning" %>
                  <%= link_to 'Destroy', task, class: "btn btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %></td>
            <% end %>
          <% end %>
          </div>
        </tr>
      <% end %>
    </table>

    <br>

    <%= submit_tag "Delete selected", class: "btn btn-primary" %>
    <button name="button" type="button" data-checkall="true" class="btn btn-default batch-del batch-del-checkall">Check All</button>
    <button name="button" type="button" data-checkall="false" class="btn btn-default batch-del batch-del-checkall">Uncheck all</button>
    <br>
    <br>

    <%= link_to 'New Task', new_task_path, class: "btn btn-info" %>

<% end %>



</div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<%= form_tag delete_multiple_tasks_path, method: :delete do %>

<!DOCTYPE html>
  <html lang="en">
  <head>
    <style>
      a.btn:not(.btn-info) {
        display: none;
      }

      td:hover .btn {
        display: inline-block;
      }
    </style>
  </head>

  <div class="col-md-10 col-md-offset-1">
    <% if user_signed_in? %>
      <span>Hello, <%= current_user.full_name %></span>
      <%= link_to 'Log out', destroy_user_session_path, :method => :delete %>
    <% else %>
      <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
      <%= link_to 'Log in', new_user_session_path %>
      or <%= link_to 'Registration', new_user_registration_path %>
    <% end %>


    <div class='container page-content' id='page-content'>
      <div id="flash-messages">
        <div class="alert alert-success alert-noajax">Signed in successfully.</div>
      </div>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <table class="table table-striped" id="tableID">

      <tr>
        Sort by
        <%= link_to 'Created Date', tasks_path(sort: 'created_at'), class: "btn btn-info" %>
        <br>
        <br>
        Sort by
        <%= link_to 'Title', tasks_path(sort: 'title'), class: "btn btn-info" %>


        <h2 class='page-heading'>Tasks</h2>

      </tr>
      <tr>
        <td class="col-md-1">ToDo</td>
      </tr>
      <% @tasks.each do |task| %>
        <tr>
          <% unless task.done %>
            <% if task.user_id == current_user.id %>
              <div class="row">
                <td><%= check_box_tag "cb_tasks[]", task.id %>
                  <%= link_to task.title, task, class: "btn btn-info" %></td>
                <td><%= link_to 'Edit', edit_task_path(task.id), class: "btn btn-primary" %>
                  <%= link_to 'Mark as done', change_to_done_path(task.id), class: "btn btn-warning" %>
                  <%= link_to 'Destroy', task, class: "btn btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %></td>
            <% end %>
          <% end %>
          </div>
        </tr>
      <% end %>
    </table>

    <br>

    <table class="table table-striped">
      <tr>
        <td class="col-md-1">Done</td>
      </tr>
      <% @tasks.each do |task| %>
        <tr>
          <% if task.done %>
            <% if task.user_id == current_user.id %>
              <td><%= check_box_tag "cb_tasks[]", task.id %>
                <%= link_to task.title, task, class: "btn btn-info" %></td>

              <td><%= link_to 'Edit', edit_task_path(task), class: "btn btn-primary" %>
                <%= link_to 'Mark as to do', change_to_todo_path(task.id), class: "btn btn-success" %>
                <%= link_to 'Destroy', task, class: "btn btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </table>

    <%= submit_tag "batch delete", class: "btn btn-danger" %>
    <button name="button" onclick="toggle(true)" type="button" data-checkall="true" class="btn btn-default">Check All
    </button>
    <button name="button" onclick="toggle(false)" type="button" data-checkall="false" class="btn btn-default">Uncheck
      all
    </button>
    <br>
    <br>

    <%= link_to 'New Task', new_task_path, class: "btn btn-info" %>


    <!-- js script for checking or unchecking checkboxes with buttons -->
    <script language="JavaScript">
        function toggle(state) {
            var checkboxes = document.getElementsByName('cb_tasks[]');
            var n = checkboxes.length;
            for (var i = 0; i < n; i++) {
                checkboxes[i].checked = state;
            }
        }
    </script>



<% end %>



</div>

app/views/tasks/index_sort_by_title.html.erb
<%= form_tag delete_multiple_tasks_path, method: :delete do %>

<!DOCTYPE html>
  <html lang="en">
  <head>
    <style>
      a.btn:not(.btn-info) {
        display: none;
      }

      .table:hover .btn {
        display: inline-block;
      }
    </style>
  </head>

  <div class="col-md-25 col-md-offset-1">
    <% if user_signed_in? %>
      <span>Hello, <%= current_user.email %></span>
      <%= link_to 'Log out', destroy_user_session_path, class: "btn btn-danger", :method => :delete %>
    <% else %>
      <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
      <%= link_to 'Log in', new_user_session_path %>
      or <%= link_to 'Registration', new_user_registration_path %>
    <% end %>


    <div class='container page-content' id='page-content'>
      <div id="flash-messages">
        <div class="alert alert-success alert-noajax">Signed in successfully.</div>
      </div>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <table class="table table-striped">

      <tr>
        <ul class="button-group">
          Sort by: &nbsp;
          <li><%= sortable 'Title', 'name', 'asc' %></li>
          <li><%= sortable 'Created Date', 'created_at', 'date' %></li>
        </ul>
        <%= link_to 'Mark as done', index_sort_by_title_path, class: "btn btn-info" %>

      </tr>
      <tr>
        <td class="col-md-1">ToDo</td>
      </tr>
      <% @tasks.each do |task| %>
        <tr>
          <% unless task.done %>
            <% if task.user_id == current_user.id %>
              <td><%= check_box_tag "cb_tasks[]", task.id %>
                <%= link_to task.title, task, class: "btn btn-info" %></td>
              <td><%= link_to 'Edit', edit_task_path(task.id), class: "btn btn-primary" %>
                <%= link_to 'Mark as done', change_to_done_path(task.id), class: "btn btn-warning" %>
                <%= link_to 'Destroy', task, class: "btn btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </table>

    <br>

    <table class="table table-striped">
      <tr>
        <td class="col-md-1">Done</td>
      </tr>
      <% @tasks.each do |task| %>
        <tr>
          <% if task.done %>
            <% if task.user_id == current_user.id %>
              <td><%= check_box_tag "cb_tasks[]", task.id %>
                <%= link_to task.title, task, class: "btn btn-info" %></td>

              <td><%= link_to 'Edit', edit_task_path(task), class: "btn btn-primary" %>
                <%= link_to 'Mark as to do', change_to_todo_path(task.id), class: "btn btn-success" %>
                <%= link_to 'Destroy', task, class: "btn btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </table>

    <%= submit_tag "Delete selected", class: "btn btn-primary" %>
    <%= submit_tag "Check all", class: "btn btn-primary" %>
    <br>
    <br>

    <%= link_to 'New Task', new_task_path, class: "btn btn-info" %>

<% end %>



</div>

app/views/tasks/new.html.erb
<h1 align="center">New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path, class: "btn btn-default"%>

app/views/tasks/show.html.erb
<div class="col-md-2 col-md-offset-5">
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Due:</strong>
  <%= @task.due %>
</p>

<p>
  <strong>Done:</strong>
  <%= @task.done %>
</p>

<%= link_to 'Edit', edit_task_path(@task), class: "btn btn-default" %> |
<%= link_to 'Back', tasks_path, class: "btn btn-default" %>
</div>

app/views/tasks/test.html.erb
<%= form_tag delete_multiple_tasks_path, method: :delete do %>
  <% if user_signed_in? %>
    <span>Здравствуйте, <%= current_user.email %></span>
    <%= link_to 'Log out', destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
    <%= link_to 'Log in', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
  <% end %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="container">
    <div class="row">
      <div class="col">
      <th colspan="2">Tasks<br></th>
      </div>
    <ul class="button-group">
      Sort by: &nbsp;
      <li><%= sortable 'Title', 'name', 'asc' %></li>
      <li><%= sortable 'Created Date', 'created_at', 'asc' %></li>
    </ul>
    <tr>
      <td>Done</td>
    </tr>
    <% @tasks.each do |task| %>
      <tr>
        <% if task.done %>
          <td><%= check_box_tag "cb_tasks[]", task.id %></td>
          <td><%= link_to task.title, task %></td>
          <% if task.user_id == current_user.id %>
            <td><%= link_to 'Edit', edit_task_path(task) %></td>
            <td><%= link_to 'Mark as to do', change_to_todo_path(task.id) %></td>
            <td><%= link_to 'Destroy', task, method: :delete, data: {confirm: 'Are you sure?'} %></td>
            <% end %><% end %>
      </tr>
    <% end %>
    </div>
  </div>

  <table>
    <tr>
      <th colspan="2">Tasks<br></th>
    </tr>
    <tr>
      <td>ToDo</td>
    </tr>
    <% @tasks.each do |task| %>
      <tr>
        <% unless task.done %>
          <td><%= check_box_tag "cb_tasks[]", task.id %></td>
          <td><%= link_to task.title, task %></td>
          <% if task.user_id == current_user.id %>
            <td><%= link_to 'Edit', edit_task_path(task.id) %></td>
            <td><%= link_to 'Mark as done', change_to_done_path(task.id) %></td>
            <td><%= link_to 'Destroy', task, method: :delete, data: {confirm: 'Are you sure?'} %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </table>

  <%= submit_tag "Delete selected" %>
  <br>

  <%= link_to 'New Task', new_task_path %>

<% end %>